UmbraSpaceIndustries/CommunityResourcePack

GameData/CommunityResourcePack/CommonResources.cfg
Appears that these did not propagate from the sheet correctly.
=> Fixed NFT resource costs/densities

GameData/CommunityResourcePack/CommonResources.cfg
LqdDeuterium, ArgonGas, LqdTritium, Lithium costs changed
=> Updated resource costs

GameData/CommunityResourcePack/CommonResources.cfg
Cost CarbonDioxide  = Density CarbonDioxide   /  Density LqdCO2  *  Cost LqdCO2  = 0.000001951 / 0.0011735 * 0.0017247 = 0.0000028637
=> Adjusted Cost CarbonDioxide to cost LqdCO2

GameData/CommunityResourcePack/CommonResources.cfg
=> Added LqdCO, an stable propellant and important ISRU resource

GameData/CommunityResourcePack/ResourceConfigs/CarbonDioxide.cfg
I've added a Sabatier reactor to the stock ISRU, and this allows air intakes to obtain CO2 from the atmosphere.
I've modeled Eve, Kerbin, and Duna against the atmospheres of Venus, Earth, and Mars, but I'm open to any values for Laythe.
=> Add atmospheric carbon dioxide

GameData/CommunityResourcePack/CommonResources.cfg
Added hsp for a lot of RF resources, added a few new resources (Ethanol alone, Ethanol 90%, MON25), corrected Ethanol75 density (it was for pure Ethanol before).
=> Add hsps, ethanol itself and 90% ethanol, MON25

GameData/CommunityResourcePack/ResourceConfigs/Karbonite.cfg
Adds intra-biome abundance variance to planetary Karbonite deposits.
=> Fixes #45 and fixes BobPalmer/Karbonite#185

GameData/CommunityResourcePack/CommonResources.cfg
=> Restored density and cost of Liquid Helium 3 to Fractals original values

GameData/CommunityResourcePack/CommonResources.cfg
Ammonia (gas), Carbon (solid), and Carbon Monoxide (gas).
=> Adding ISRU intermediates.

GameData/CommunityResourcePack/CommonResources.cfg
Reverts BobPalmer/CommunityResourcePack#70
=> Revert "Adding ISRU intermediates."

GameData/CommunityResourcePack/CommonResources.cfg, GameData/CommunityResourcePack/ResourceConfigs/Dirt.cfg
Added MaterialKits, Dirt, ExoticMinerals and RareMetals to the CommonResources.cfg
Added Dirt.cfg to the ResourceConfigs folder
=> Added MaterialKits and MKS-L Resources

GameData/CommunityResourcePack/CommonResources.cfg
required for for correct functionality KSPI reactors and engines
=> Reintroduction of UF4 and restoration ALL_VESSEL  for ThF4 flowmode

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
The cost of Plutonium-238 was way too low
Although at current real world price would make it cost 19900, I only Increased the cost of Plutonium to 4000 (about 5 times as expansive as Enriched Uranium)
=> Increased the cost of Plutonium

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
LqdHe3 is very hard to store Cryogenic, also mining LqdHe3 would be kind of unrealistic
=> Added non liquid Helium3 resource for Surface Mining and Non Cryogenic storage

FOR_RELEASE/GameData/CommunityResourcePack/ResourceConfigs/LqdHe3.cfg
=> Added resource definition for Helium3

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
=> Lowered cost of Tritium and Helium3 by a factor of 10

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
SolarWind consists out of the charged particles emitted by the sun
=> Added Resource SolarWind

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Sodium, a relatively common resource, shows great potential as an electric propellant
=> Added common resource Sodium a potential high efficient electric propellant

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
=> Added common resource Caesium a rare but dense and highly efficient electric propellant

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Cost based on cost existing gas versions
=> Added Liquid versions of Krypton and Neon

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Adjusted cost of lithium based on real cost difference with Pure Hydrogen
=> Increased the cost of Lithium

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Based cost on proposed cost LqdAmmonia
=> Added Resource Ammonia as Gas

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Added the Cryogenically cooled version of XenonGas
=> Added Resource LqdXenon

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
=> Added Resource CarbonMonoxide as Gas

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Thorium represent Thorium 232, a fertile Nuclear Fuel, Cast Based on ThF4 and Fluorine
=> Added Resource Thorium

Rock.cfg
Created a cfg to generate ART Rock as a crustal resource.
=> Added Rock

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Nitratine is the main mantle Ore, rich in Nitrogen
=> Added resource Nitratine

FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg
Fixed Silicates and Silicon density was off by a factor of 10
=> Fixed density of Silicates and Silicon

FOR_RELEASE/GameData/CommunityResourcePack/ResourceConfigs/Regolith.cfg, FOR_RELEASE/GameData/CommunityResourcePack/ResourceConfigs/Silicates.cfg, FOR_RELEASE/GameData/CommunityResourcePack/ResourceConfigs/Spodumene.cfg, FOR_RELEASE/GameData/CommunityResourcePack/SurfaceScanner.cfg
- Modified ResourceConfig for Alumina and Silicates. Now available on almost any body.
- Added ResourceConfig for Regolith and Spodumene. Also available on most bodys.
- Added Alumina, Regolith and Spodumene to SurfaceScanner.cfg.
All modified resources are KSPI-E curated and Freethinker gave me his blessing.
=> Added/modified ResourceConfigs

FOR_RELEASE/GameData/CommunityResourcePack/Localization/fr-fr.cfg
=> French Translation

FOR_RELEASE/GameData/CommunityResourcePack/CRP.version
Is CommunityResourcePack compatible with KSP 1.9?
Click Merge for yes, Close for no.
Tagging @BobPalmer since not everyone has notifications turned on for GitHub pull requests.
=> Update version file for KSP 1.9 compatibility

FOR_RELEASE/GameData/CommunityResourcePack/Localization/zh-cn.cfg
=> Chinese translation error correction

FOR_RELEASE/GameData/CommunityResourcePack/CRP.version
make ckan etc happy, this doesn't need per-ksp-release rebuilds based on discussion in forum post
https://forum.kerbalspaceprogram.com/index.php?/topic/83007-15x-community-resource-pack/page/57/#replyForm&ct=1598483316
=> remove max bound on version
